---
type: specs.openrewrite.org/v1beta/recipe
name: org.mockbukkit.rewrite.PackageRename
displayName: Replace be.seeseemelk.mockbukkit Package with org.mockbukkit.mockbukkit package
recipeList:
  - org.openrewrite.java.ChangePackage:
      oldPackageName: be.seeseemelk.mockbukkit
      newPackageName: org.mockbukkit.mockbukkit
...